# Generated by Django 5.0.4 on 2026-09-05 22:26

import django.db.models.deletion
import prblm_mailer.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter', '0014_article_image_below_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('newsletter.subscription',),
        ),
        migrations.CreateModel(
            name='SubscriberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text="The group this answer belongs to, e.g. 'Interest'.", max_length=80)),
                ('value_slug', models.SlugField(max_length=80)),
                ('value_label', models.CharField(max_length=160)),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='tags', to='newsletter.subscription')),
            ],
            options={
                'verbose_name': 'subscriber group',
                'verbose_name_plural': 'subscriber groups',
                'ordering': ['group_name', 'value_label'],
                'unique_together': {('group_name', 'value_slug')},
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='The email subject line.', max_length=255)),
                ('body', wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_link', wagtail.blocks.URLBlock(label='Image links to', required=False)), ('text', wagtail.blocks.CharBlock(label='Text', required=False)), ('text_link', wagtail.blocks.URLBlock(label='Text links to', required=False)), ('color1', prblm_mailer.blocks.ColorBlock(label='Background colour 1')), ('color2', prblm_mailer.blocks.ColorBlock(label='Background colour 2 (makes a gradient)')), ('image_width', wagtail.blocks.ChoiceBlock(choices=[('40', '40px'), ('50', '50px'), ('60', '60px'), ('80', '80px'), ('100', '100px'), ('120', '120px'), ('150', '150px'), ('180', '180px'), ('220', '220px')], label='Image size')), ('image_side', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image left'), ('right', 'Image right')], label='When both: image on')), ('text_color', wagtail.blocks.ChoiceBlock(choices=[('dark', 'Dark (near-black)'), ('light', 'Light (white)')], label='Text colour'))])), ('content', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Heading', required=False)), ('description', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link'], label='Description', required=False)), ('text_width', wagtail.blocks.ChoiceBlock(choices=[('full', 'Full'), ('wide', 'Wide'), ('medium', 'Medium'), ('narrow', 'Narrow')], help_text='Narrows the description text only.', label='Text width')), ('align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], label='Align')), ('button_text', wagtail.blocks.CharBlock(label='Button label', required=False)), ('button_url', wagtail.blocks.URLBlock(label='Button links to', required=False)), ('button_color1', prblm_mailer.blocks.ColorBlock(label='Button colour 1')), ('button_color2', prblm_mailer.blocks.ColorBlock(label='Button colour 2 (gradient)')), ('button_text_color', prblm_mailer.blocks.ColorBlock(label='Button text colour')), ('text_color', wagtail.blocks.ChoiceBlock(choices=[('dark', 'Dark (near-black)'), ('light', 'Light (white)')], label='Text colour')), ('color1', prblm_mailer.blocks.ColorBlock(label='Background colour 1')), ('color2', prblm_mailer.blocks.ColorBlock(label='Background colour 2 (makes a gradient)'))])), ('two_column', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Column image')), ('heading', wagtail.blocks.CharBlock(label='Heading', required=False)), ('description', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link'], label='Description', required=False)), ('button_text', wagtail.blocks.CharBlock(label='Button label', required=False)), ('button_url', wagtail.blocks.URLBlock(label='Button links to', required=False)), ('button_color1', prblm_mailer.blocks.ColorBlock(label='Button colour 1')), ('button_color2', prblm_mailer.blocks.ColorBlock(label='Button colour 2 (gradient)')), ('text_color', wagtail.blocks.ChoiceBlock(choices=[('dark', 'Dark (near-black)'), ('light', 'Light (white)')], help_text='Use Light on dark backgrounds.', label='Text colour')), ('button_text_color', prblm_mailer.blocks.ColorBlock(label='Button text colour')), ('align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], label='Align')), ('image_side', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image left'), ('right', 'Image right')], label='Image on')), ('color1', prblm_mailer.blocks.ColorBlock(label='Background colour 1')), ('color2', prblm_mailer.blocks.ColorBlock(label='Background colour 2 (makes a gradient)'))])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock(label='Links to', required=False)), ('width', wagtail.blocks.ChoiceBlock(choices=[('25', '25%'), ('33', '33%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('66', '66%'), ('75', '75%'), ('80', '80%'), ('100', 'Full width')], label='Width')), ('align', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], label='Alignment'))])), ('spacer', wagtail.blocks.StructBlock([('height', wagtail.blocks.ChoiceBlock(choices=[('16', 'Small'), ('32', 'Medium'), ('56', 'Large'), ('80', 'Extra large')], label='Height')), ('divider', wagtail.blocks.BooleanBlock(label='Show a divider line', required=False)), ('line_color', prblm_mailer.blocks.ColorBlock(help_text='Blank = grey (#cccccc). Pick a darker colour to make it stand out.', label='Line colour')), ('line_width', wagtail.blocks.ChoiceBlock(choices=[('1', 'Hairline (1px)'), ('2', 'Thin (2px)'), ('3', 'Medium (3px)'), ('5', 'Thick (5px)')], label='Line thickness'))])), ('footer', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_link', wagtail.blocks.URLBlock(label='Image links to', required=False)), ('text', wagtail.blocks.CharBlock(label='Text', required=False)), ('text_link', wagtail.blocks.URLBlock(label='Text links to', required=False)), ('color1', prblm_mailer.blocks.ColorBlock(label='Background colour 1')), ('color2', prblm_mailer.blocks.ColorBlock(label='Background colour 2 (makes a gradient)')), ('image_width', wagtail.blocks.ChoiceBlock(choices=[('40', '40px'), ('50', '50px'), ('60', '60px'), ('80', '80px'), ('100', '100px'), ('120', '120px'), ('150', '150px'), ('180', '180px'), ('220', '220px')], label='Image size')), ('image_side', wagtail.blocks.ChoiceBlock(choices=[('left', 'Image left'), ('right', 'Image right')], label='When both: image on')), ('text_color', wagtail.blocks.ChoiceBlock(choices=[('dark', 'Dark (near-black)'), ('light', 'Light (white)')], label='Text colour')), ('show_unsubscribe', wagtail.blocks.BooleanBlock(default=True, label='Show the unsubscribe button', required=False))]))], help_text='Build the newsletter from email blocks. Use the + button to add one.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_html', models.TextField(blank=True)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_failed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('sent_audience', models.CharField(blank=True, max_length=500)),
                ('include_ungrouped', models.BooleanField(default=False, verbose_name='Subscribers with no group')),
                ('send_to_tags', models.ManyToManyField(blank=True, related_name='broadcasts', to='prblm_mailer.subscribertag', verbose_name='Groups to send to')),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
                'ordering': ['-created_at'],
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='prblm_mailer.broadcast')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'event'], name='prblm_maile_email_1556ab_idx')],
            },
        ),
    ]
