# Generated by Django 5.2.16 on 2026-09-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_article_image_below_text'),
        ('prblm_mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('clicked', 'Click'), ('opened', 'Open')], max_length=8)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('at', models.DateTimeField()),
                ('mailgun_event_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='prblm_mailer.broadcast')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement', to='newsletter.subscription')),
            ],
            options={
                'verbose_name': 'engagement event',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['broadcast', 'kind', 'at'], name='prblm_maile_broadca_08a505_idx'), models.Index(fields=['broadcast', 'kind', 'subscription'], name='prblm_maile_broadca_94a2c9_idx')],
            },
        ),
    ]
