# Generated by Django 5.2.16 on 2026-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupingformfield',
            name='use_for_optin',
            field=models.BooleanField(default=False, help_text='Make this checkbox decide whether the submitter joins the newsletter. Ticked = subscribe. Without such a field, every submission is offered the list.', verbose_name='Use as the newsletter opt-in'),
        ),
    ]
